name: guhio
version: 0.1.0
summary: An open source IoT server
description: The guh daemon is a plugin based IoT (Internet of Things) server. The server works like a translator for devices, things and services and allows them to interact. With the powerful rule engine you are able to connect any device available in the system and create individual scenes and behaviors for your environment.
confinement: devmode
grade: devel

apps:
  guhd:
    command: qt5-launch guhd -n -p
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - network-manager
      - network-observe
      - serial-port
      - bluetooth-control
      - avahi-observe
      - bluez
      - shutdown

  guh-cli:
    command: guh-cli
    plugs: 
      - network
      - network-bind


parts:
  # Building the whole guh project containig libguh and plugins
  guh:
    plugin: qmake
    source: ../
    options: [ CONFIG+=ccache, CONFIG+=disabletesting, CONFIG+=snappy ]
    qt-version: qt5
    project-files: [ guh.pro ]
    build-packages:
      - python
      - ccache
      - dpkg-dev
      - rsync
      - qtchooser
      - qt5-qmake
      - qtbase5-dev
      - qtbase5-dev-tools
      - qttools5-dev-tools
      - qtconnectivity5-dev
      - libqt5websockets5-dev
      - libqt5serialport5-dev
      - libqt5bluetooth5
      - libqt5sql5-sqlite
      - libqt5dbus5
      - libavahi-client-dev
      - libavahi-common-dev
    stage-packages:
      - libqt5network5
      - libqt5gui5
      - libqt5sql5
      - libqt5xml5
      - libqt5dbus5
      - libqt5websockets5
      - libqt5bluetooth5
      - libqt5sql5-sqlite
      - libqt5serialport5
      - logrotate
      - nmap
      - avahi-daemon
      - libavahi-client3
      - libavahi-common3
    after: [ qt5conf ]
    
  guh-cli:
    plugin: python
    python-version: python2
    source: https://github.com/guh/guh-cli.git
    source-type: git
    after: [ guh ]
    build-packages:
      - python-dev
      - python-pip
      - python-setuptools
    build-packages:
      - python-setuptools

  guh-webinterface:
    plugin: dump
    source: https://jenkins.guh.io/view/guh-webinterface/job/guh-webinterface-all/lastBuild/artifact/guh-webinterface.tar.gz
    source-type: tar
    after: [ guh-cli ]
    organize:
      '*': guh-webinterface/
